name: carryvibemobile
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  connectivity_plus: ^4.0.1
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.0.4
  flutter_localization: ^0.1.13
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  getwidget: ^3.1.1
  google_maps_flutter: ^2.3.1
  http: ^1.1.0
  image: ^4.0.17
  image_picker: ^1.0.2
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/
    - assets/notification.mp3

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900